# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tmgreact

on:
  push:
    branches:
      - react
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://tmgregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c9e0979363f147a29a3df7dc5fe88fd5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_182f0ca7e25c4715a564786944eae6fa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: tmgregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c9e0979363f147a29a3df7dc5fe88fd5 }}/tmgimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tmgreact'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9608392073924acf9457f92dddf471eb }}
        images: 'tmgregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c9e0979363f147a29a3df7dc5fe88fd5 }}/tmgimage:${{ github.sha }}'